# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hardik Chauhan
full_name: Hardik Chauhan
email: chauhanhardik23@gmail.com
#email2: kalpesh@cs.umass.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://backpropagator.github.io" # the base hostname & protocol for your site
github_username:  hardik2396
twitter_username: backpropagater
linkedin_username: hardikchauhan2396
#stackoverflow: 5080995/martianwars
include: ['_pages']
footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
